apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::211289421537:role/eksctl-credcars-cluster-nodegroup--NodeInstanceRole-YT5NMwI1psdn
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::211289421537:user/github-deployer-staging
      username: github-deployer-staging
      groups:
        - system:masters
