apiVersion: apps/v1
kind: Deployment
metadata:
  name: credcars-backend
  namespace: staging  # replaced dynamically by GitHub Actions
  labels:
    app: credcars-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: credcars-backend
  template:
    metadata:
      labels:
        app: credcars-backend
    spec:
      containers:
        - name: backend
          image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/<ECR_BACKEND>:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: credcars-backend-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
