apiVersion: apps/v1
kind: Deployment
metadata:
  name: credcars-backend
  namespace: production
  labels:
    app: credcars-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: credcars-backend
  template:
    metadata:
      labels:
        app: credcars-backend
      annotations:
        # This annotation forces a rollout whenever the config/secret changes
        configmap-last-updated: "{{ .ConfigMapVersion }}"
        secret-last-updated: "{{ .SecretVersion }}"
    spec:
      containers:
        - name: credcars-backend
          image: 211289421537.dkr.ecr.us-east-1.amazonaws.com/credcars-backend:latest

          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: credcars-backend-config
            - secretRef:
                name: credcars-backend-secrets
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
      imagePullSecrets:
        - name: ecr-creds
